//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingRulesCost
    {
        public int CostID { get; set; }
        public int RuleID { get; set; }
        public int GroupID { get; set; }
        public Nullable<decimal> CostMultipliedBy { get; set; }
        public Nullable<decimal> CostDividedBy { get; set; }
        public Nullable<byte> IsSkipRest { get; set; }
        public int Seq { get; set; }
    
        public virtual BillingRules BillingRules { get; set; }
        public virtual BillingRulesGroup BillingRulesGroup { get; set; }
    }
}
