//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingRules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingRules()
        {
            this.BillingRulesCost = new HashSet<BillingRulesCost>();
        }
    
        public int RuleID { get; set; }
        public string RuleName { get; set; }
        public string RuleDescription { get; set; }
        public string CalculateOn { get; set; }
        public string CalculateField { get; set; }
        public string ApplyCondition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingRulesCost> BillingRulesCost { get; set; }
    }
}
