//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackBoxTransaction
    {
        public int ID { get; set; }
        public int BlackBoxID { get; set; }
        public string BBStatus { get; set; }
        public Nullable<bool> IsCollectionDeposit { get; set; }
        public string CollectionMode { get; set; }
        public string NameOnCard { get; set; }
        public string BankName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> DateOfCheque { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> DroneID { get; set; }
        public Nullable<int> ApprovalID { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> RentStartDate { get; set; }
        public Nullable<System.DateTime> RentEndDate { get; set; }
        public string RentType { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public string VerifyCode { get; set; }
        public Nullable<bool> RentAcknowledged { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.TimeSpan> RentEndTime { get; set; }
        public Nullable<System.TimeSpan> RentStartTime { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.TimeSpan> ReceivedTime { get; set; }
        public string EncryptionKey { get; set; }
        public Nullable<int> WHoursCount { get; set; }
        public Nullable<int> OHoursCount { get; set; }
        public Nullable<int> SNoticeCount { get; set; }
        public string ReceivedFrom { get; set; }
    }
}
