//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentManagement
    {
        public int CmsID { get; set; }
        public string CmsRefName { get; set; }
        public int IsShowInMenu { get; set; }
        public string PageTitle { get; set; }
        public string Body { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string MenuTitle { get; set; }
    }
}
