//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneCheckListItem
    {
        public int ID { get; set; }
        public Nullable<int> DroneCheckListID { get; set; }
        public string FieldValue { get; set; }
        public string FieldNote { get; set; }
        public Nullable<int> DroneCheckListItemID { get; set; }
    }
}
