//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneData
    {
        public Nullable<int> DroneId { get; set; }
        public string DroneRFID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string ProductRFID { get; set; }
        public string ProductQrCode { get; set; }
        public string ProductRSSI { get; set; }
        public string ReadTime { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Altitude { get; set; }
        public string Speed { get; set; }
        public string FixQuality { get; set; }
        public string Satellites { get; set; }
        public string Pitch { get; set; }
        public string Roll { get; set; }
        public string Heading { get; set; }
        public string TotalFlightTime { get; set; }
        public string BBFlightID { get; set; }
        public Nullable<int> IsProcessed { get; set; }
        public string QueueMessage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Voltage { get; set; }
        public Nullable<bool> IsLogData { get; set; }
        public int BlackBoxID { get; set; }
        public int BlackBoxSerial { get; set; }
        public string Yaw { get; set; }
        public int DroneDataID { get; set; }
        public Nullable<int> RSSI { get; set; }
        public string CellOperator { get; set; }
        public Nullable<decimal> IMU_GX { get; set; }
        public Nullable<decimal> IMU_GY { get; set; }
        public Nullable<decimal> IMU_GZ { get; set; }
        public Nullable<decimal> IMU_AX { get; set; }
        public Nullable<decimal> IMU_AY { get; set; }
        public Nullable<decimal> IMU_AZ { get; set; }
        public Nullable<decimal> IMU_MX { get; set; }
        public Nullable<decimal> IMU_MY { get; set; }
        public Nullable<decimal> IMU_MZ { get; set; }
        public Nullable<decimal> BMP { get; set; }
        public Nullable<int> SD_Logging { get; set; }
        public Nullable<int> Cell_RSSI { get; set; }
        public Nullable<int> Cell_CCID { get; set; }
        public Nullable<int> Cell_SIM { get; set; }
        public Nullable<decimal> Cell_Voltage { get; set; }
        public Nullable<int> Debug { get; set; }
        public Nullable<int> Cell_MissedLog { get; set; }
        public string Cell_Operator { get; set; }
    }
}
