//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneDocuments
    {
        public int ID { get; set; }
        public int DroneID { get; set; }
        public string DocumentType { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<int> FlightID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentDesc { get; set; }
        public string S3Url { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public string DCAADocType { get; set; }
        public Nullable<int> DCAADocID { get; set; }
    }
}
