//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DroneCheckListValidation
    {
        public int ID { get; set; }
        public Nullable<int> DroneID { get; set; }
        public Nullable<int> DroneCheckListID { get; set; }
        public Nullable<int> DroneCheckListItemID { get; set; }
        public Nullable<decimal> MinValue { get; set; }
        public Nullable<decimal> MaxValue { get; set; }
        public Nullable<bool> CanBeIgnored { get; set; }
        public Nullable<bool> MustBeChecked { get; set; }
    }
}
