//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCA_Approval
    {
        public int ApprovalID { get; set; }
        public string ApprovalName { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Coordinates { get; set; }
        public System.Data.Entity.Spatial.DbGeography Polygon { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DroneID { get; set; }
        public string ApprovalFileUrl { get; set; }
        public string EndTime { get; set; }
        public string StartTime { get; set; }
        public System.Data.Entity.Spatial.DbGeography InnerBoundary { get; set; }
        public string InnerBoundaryCoord { get; set; }
        public Nullable<int> BoundaryInMeters { get; set; }
        public Nullable<int> MinAltitude { get; set; }
        public Nullable<int> MaxAltitude { get; set; }
        public Nullable<int> MinDefault { get; set; }
        public Nullable<int> MaxDefault { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public bool IsUseCamara { get; set; }
        public string MOD_ApprovalURL { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovalRemarks { get; set; }
        public Nullable<int> PilotUserId { get; set; }
        public Nullable<int> GroundStaffUserId { get; set; }
        public string NotificationEmails { get; set; }
        public Nullable<int> CameraId { get; set; }
        public int RpasApprovalRefNum { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string notam { get; set; }
        public string DCAA_ApprovalID { get; set; }
    }
}
