//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip2location
    {
        public double ip_from { get; set; }
        public double ip_to { get; set; }
        public string country_code { get; set; }
        public string country_name { get; set; }
    }
}
