//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUP_Product
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> Code { get; set; }
        public string TypeId { get; set; }
        public string BinaryCode { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AccountId { get; set; }
    }
}
