//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExponentPortal : DbContext
    {
        public ExponentPortal()
            : base("name=ExponentPortal")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADSBData> ADSBData { get; set; }
        public virtual DbSet<AgriTraxImages> AgriTraxImages { get; set; }
        public virtual DbSet<AgriTraxManagement> AgriTraxManagement { get; set; }
        public virtual DbSet<ApproalDetail> ApproalDetail { get; set; }
        public virtual DbSet<BillingRules> BillingRules { get; set; }
        public virtual DbSet<BillingRulesCost> BillingRulesCost { get; set; }
        public virtual DbSet<BillingRulesGroup> BillingRulesGroup { get; set; }
        public virtual DbSet<BlackBoxCost> BlackBoxCost { get; set; }
        public virtual DbSet<BlackBoxLog> BlackBoxLog { get; set; }
        public virtual DbSet<BlackBoxTransaction> BlackBoxTransaction { get; set; }
        public virtual DbSet<CommsDetail> CommsDetail { get; set; }
        public virtual DbSet<ContentManagement> ContentManagement { get; set; }
        public virtual DbSet<DroneCheckList> DroneCheckList { get; set; }
        public virtual DbSet<DroneCheckListItem> DroneCheckListItem { get; set; }
        public virtual DbSet<DroneCheckListValidation> DroneCheckListValidation { get; set; }
        public virtual DbSet<DroneData> DroneData { get; set; }
        public virtual DbSet<DroneDefinition> DroneDefinition { get; set; }
        public virtual DbSet<DroneDocuments> DroneDocuments { get; set; }
        public virtual DbSet<DroneFlight> DroneFlight { get; set; }
        public virtual DbSet<DroneFlightVideo> DroneFlightVideo { get; set; }
        public virtual DbSet<DroneGPSLog> DroneGPSLog { get; set; }
        public virtual DbSet<FlightInfo> FlightInfo { get; set; }
        public virtual DbSet<FlightMapData> FlightMapData { get; set; }
        public virtual DbSet<GCA_Approval> GCA_Approval { get; set; }
        public virtual DbSet<LiveDrone> LiveDrone { get; set; }
        public virtual DbSet<LUP_Drone> LUP_Drone { get; set; }
        public virtual DbSet<LUP_Product> LUP_Product { get; set; }
        public virtual DbSet<M2M_Drone_User> M2M_Drone_User { get; set; }
        public virtual DbSet<M2M_DroneDetails> M2M_DroneDetails { get; set; }
        public virtual DbSet<M2M_DroneParts> M2M_DroneParts { get; set; }
        public virtual DbSet<M2M_DroneServiceParts> M2M_DroneServiceParts { get; set; }
        public virtual DbSet<M2M_ProfileMenu> M2M_ProfileMenu { get; set; }
        public virtual DbSet<M2M_UserAccount> M2M_UserAccount { get; set; }
        public virtual DbSet<MSTR_Account> MSTR_Account { get; set; }
        public virtual DbSet<MSTR_BlackBox> MSTR_BlackBox { get; set; }
        public virtual DbSet<MSTR_CheckList_Drone> MSTR_CheckList_Drone { get; set; }
        public virtual DbSet<MSTR_CheckListItems_Drone> MSTR_CheckListItems_Drone { get; set; }
        public virtual DbSet<MSTR_Comms> MSTR_Comms { get; set; }
        public virtual DbSet<MSTR_Drone> MSTR_Drone { get; set; }
        public virtual DbSet<MSTR_Drone_Setup> MSTR_Drone_Setup { get; set; }
        public virtual DbSet<MSTR_DroneCheckList> MSTR_DroneCheckList { get; set; }
        public virtual DbSet<MSTR_DroneCheckListItems> MSTR_DroneCheckListItems { get; set; }
        public virtual DbSet<MSTR_DroneService> MSTR_DroneService { get; set; }
        public virtual DbSet<MSTR_Menu> MSTR_Menu { get; set; }
        public virtual DbSet<MSTR_NOC> MSTR_NOC { get; set; }
        public virtual DbSet<MSTR_NoFlyZone> MSTR_NoFlyZone { get; set; }
        public virtual DbSet<MSTR_Parts> MSTR_Parts { get; set; }
        public virtual DbSet<MSTR_Pilot_Log> MSTR_Pilot_Log { get; set; }
        public virtual DbSet<MSTR_Product> MSTR_Product { get; set; }
        public virtual DbSet<MSTR_Profile> MSTR_Profile { get; set; }
        public virtual DbSet<MSTR_RPAS_User> MSTR_RPAS_User { get; set; }
        public virtual DbSet<MSTR_TrafficMonitor> MSTR_TrafficMonitor { get; set; }
        public virtual DbSet<MSTR_User> MSTR_User { get; set; }
        public virtual DbSet<MSTR_User_Pilot> MSTR_User_Pilot { get; set; }
        public virtual DbSet<MSTR_User_Pilot_Certification> MSTR_User_Pilot_Certification { get; set; }
        public virtual DbSet<MSTR_User_Pilot_ExponentUAS> MSTR_User_Pilot_ExponentUAS { get; set; }
        public virtual DbSet<NOC_Details> NOC_Details { get; set; }
        public virtual DbSet<PayLoad_AutoFix> PayLoad_AutoFix { get; set; }
        public virtual DbSet<PayLoadData> PayLoadData { get; set; }
        public virtual DbSet<PayLoadDataGPS> PayLoadDataGPS { get; set; }
        public virtual DbSet<PayloadDataGridLines> PayloadDataGridLines { get; set; }
        public virtual DbSet<PayLoadDataRFID> PayLoadDataRFID { get; set; }
        public virtual DbSet<PayLoadYard> PayLoadYard { get; set; }
        public virtual DbSet<PortalAlert> PortalAlert { get; set; }
        public virtual DbSet<PortalAlertEmail> PortalAlertEmail { get; set; }
        public virtual DbSet<PortalAlertRegistration> PortalAlertRegistration { get; set; }
        public virtual DbSet<PortalAuth> PortalAuth { get; set; }
        public virtual DbSet<POS_Customer> POS_Customer { get; set; }
        public virtual DbSet<POS_Organization> POS_Organization { get; set; }
        public virtual DbSet<POS_Shop> POS_Shop { get; set; }
        public virtual DbSet<ProductDefinition> ProductDefinition { get; set; }
        public virtual DbSet<ProductHistory> ProductHistory { get; set; }
        public virtual DbSet<ProductTransactions> ProductTransactions { get; set; }
        public virtual DbSet<SMSTable> SMSTable { get; set; }
        public virtual DbSet<TrafficData> TrafficData { get; set; }
        public virtual DbSet<TrafficMonitor> TrafficMonitor { get; set; }
        public virtual DbSet<UserLog> UserLog { get; set; }
        public virtual DbSet<UserRPASPermit> UserRPASPermit { get; set; }
        public virtual DbSet<BlackBoxData> BlackBoxData { get; set; }
        public virtual DbSet<DCAA_PermitDetail> DCAA_PermitDetail { get; set; }
        public virtual DbSet<ip2location> ip2location { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<PayloadDataGrid> PayloadDataGrid { get; set; }
        public virtual DbSet<PayLoadFlight> PayLoadFlight { get; set; }
        public virtual DbSet<PayLoadImageData> PayLoadImageData { get; set; }
        public virtual DbSet<PayLoadMapData> PayLoadMapData { get; set; }
        public virtual DbSet<PayloadTraffic> PayloadTraffic { get; set; }
        public virtual DbSet<PayLoadYardGrid> PayLoadYardGrid { get; set; }
        public virtual DbSet<SimulatorFlights> SimulatorFlights { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
