//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_User_Pilot
    {
        public string PassportNo { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public string Department { get; set; }
        public string EmiratesId { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
    }
}
