//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_Menu
    {
        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string PageUrl { get; set; }
        public string ControllerName { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string PermissionId { get; set; }
    }
}
