//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_DroneService
    {
        public int ServiceId { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> AcceptedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> AcceptedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<int> DroneId { get; set; }
        public string TypeOfService { get; set; }
        public Nullable<int> FlightHour { get; set; }
        public Nullable<System.DateTime> DateOfService { get; set; }
        public Nullable<int> TypeOfServiceId { get; set; }
    }
}
