//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_CheckList_Drone
    {
        public int ID { get; set; }
        public string CheckListTitle { get; set; }
        public string CheckListSubTitle { get; set; }
        public Nullable<int> DroneID { get; set; }
    }
}
