//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSTR_User_Pilot_ExponentUAS
    {
        public Nullable<int> CertificateId { get; set; }
        public Nullable<System.DateTime> DateOfEnrollement { get; set; }
        public Nullable<System.DateTime> DateOfCertification { get; set; }
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
