//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nationality
    {
        public int NationalityID { get; set; }
        public string Country { get; set; }
        public string Abbreviation { get; set; }
        public string Adjective { get; set; }
        public string Person { get; set; }
    }
}
