//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadYard
    {
        public int YardID { get; set; }
        public int AccountID { get; set; }
        public string YardName { get; set; }
        public Nullable<decimal> TopLeftLat { get; set; }
        public Nullable<decimal> TopLeftLon { get; set; }
        public Nullable<decimal> TopRightLat { get; set; }
        public Nullable<decimal> TopRightLon { get; set; }
        public Nullable<decimal> BottomLeftLat { get; set; }
        public Nullable<decimal> BottomLeftLon { get; set; }
        public Nullable<decimal> BottomRightLat { get; set; }
        public Nullable<decimal> BottomRightLon { get; set; }
        public string VechileOrientation { get; set; }
        public Nullable<int> VechileLength { get; set; }
        public Nullable<int> VechileWidth { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public int Rows { get; set; }
        public int Columns { get; set; }
    }
}
