//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadDataGPS
    {
        public long id { get; set; }
        public string FlightUniqueID { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<System.DateTime> GPSDate { get; set; }
        public Nullable<int> Satellite { get; set; }
        public Nullable<byte> IsSend { get; set; }
    }
}
