//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadImageData
    {
        public int PayLoadImageDataID { get; set; }
        public string PayLoadFlightID { get; set; }
        public string DroneId { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> ImageCreatedDate { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string GPSFix { get; set; }
        public string LogFilePath { get; set; }
    }
}
