//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadDataRFID
    {
        public int PayLoadDataRFIDID { get; set; }
        public string FlightUniqueID { get; set; }
        public string RFID { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> Col { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Lng { get; set; }
        public Nullable<System.DateTime> ReadMinDate { get; set; }
        public Nullable<System.DateTime> RadMaxDate { get; set; }
        public Nullable<int> MaxRSSI { get; set; }
        public Nullable<int> MinRSSI { get; set; }
    }
}
