//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadMapData
    {
        public int PayLoadDataMapID { get; set; }
        public string FlightUniqueID { get; set; }
        public string DroneId { get; set; }
        public string RFID { get; set; }
        public string ProductQrCode { get; set; }
        public Nullable<int> RSSI { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public Nullable<int> ReadFreq { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<System.DateTime> GPSTime { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> FlightID { get; set; }
        public string GPSFix { get; set; }
        public Nullable<decimal> RFIDAverage { get; set; }
        public Nullable<int> RFIDMin { get; set; }
        public Nullable<System.DateTime> LastProcessed { get; set; }
        public string IsProcessed { get; set; }
        public Nullable<int> YardID { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
        public Nullable<int> CellID { get; set; }
        public Nullable<int> MaxCellID { get; set; }
        public Nullable<int> MaxRow { get; set; }
        public Nullable<int> MaxCol { get; set; }
        public Nullable<decimal> RowDistance { get; set; }
        public Nullable<decimal> ColDistance { get; set; }
        public Nullable<decimal> ColPointLat { get; set; }
        public Nullable<decimal> ColPointLon { get; set; }
        public Nullable<decimal> RowPointLat { get; set; }
        public Nullable<decimal> RowPointLon { get; set; }
        public Nullable<int> RowFixExecuted { get; set; }
        public Nullable<int> ColFixExecuted { get; set; }
        public Nullable<int> AutoFixCol1 { get; set; }
        public Nullable<int> AutoFixGap { get; set; }
        public string ShelfID { get; set; }
        public Nullable<int> IsValid { get; set; }
        public Nullable<int> ProcessingModel { get; set; }
        public Nullable<decimal> GridLat { get; set; }
        public Nullable<decimal> GridLng { get; set; }
    }
}
