//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayLoadYardGrid
    {
        public int CellID { get; set; }
        public int YardID { get; set; }
        public Nullable<int> CellNumber { get; set; }
        public Nullable<decimal> TopLeftLat { get; set; }
        public Nullable<decimal> TopLeftLon { get; set; }
        public Nullable<decimal> TopRightLat { get; set; }
        public Nullable<decimal> TopRightLon { get; set; }
        public Nullable<decimal> BottomLeftLat { get; set; }
        public Nullable<decimal> BottomLeftLon { get; set; }
        public Nullable<decimal> BottomRightLat { get; set; }
        public Nullable<decimal> BottomRightLon { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<int> ColumnNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.Data.Entity.Spatial.DbGeography Polygon { get; set; }
    }
}
