//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Shop
    {
        public int ShopID { get; set; }
        public int OrganizationID { get; set; }
        public string ShopLocation { get; set; }
        public string ShopName { get; set; }
        public string ShopEmail { get; set; }
        public string ShopTelephone { get; set; }
        public string ShopPassword { get; set; }
    }
}
