//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Customer
    {
        public int CustomerID { get; set; }
        public int ShopID { get; set; }
        public int OrganizationID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerEmiratesID { get; set; }
        public string CustomerPassportID { get; set; }
        public string CustomerNationality { get; set; }
        public string RPASLicenseNumber { get; set; }
        public Nullable<System.DateTime> RPASLicenseExpiry { get; set; }
        public string RPASSerial { get; set; }
        public string RPASManufacture { get; set; }
        public string RPASModel { get; set; }
    }
}
