//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductHistory
    {
        public int ProHistoryId { get; set; }
        public Nullable<int> Latitude { get; set; }
        public Nullable<int> Logitude { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProRFID { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public string RSSI { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> RecordType { get; set; }
    }
}
