//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> LoggedInTime { get; set; }
        public Nullable<System.DateTime> LoggedOfTime { get; set; }
        public string UserIPAddress { get; set; }
        public string Browser { get; set; }
        public string SessionID { get; set; }
        public Nullable<System.DateTime> SessionStartTime { get; set; }
        public Nullable<System.DateTime> SessionEndTime { get; set; }
        public Nullable<bool> IsSessionEnd { get; set; }
        public string ApplicationID { get; set; }
    }
}
